from datetime import datetime, timezone, timedelta
from typing import Dict, Any, List, Optional
from core.db import list_concepts, get_or_create_course, record_event
from tools.calendar_tools import create_revision_event


def generate_revision_plan(
    learner_id: str,
    course_id: str,
    exam_date_iso: Optional[str] = None
) -> Dict[str, Any]:
    """Generate a spaced-repetition revision plan and schedule calendar blocks."""
    course = get_or_create_course(learner_id, course_id)
    course_name = course.get("title") or course_id.replace("_", " ").title()
    
    # Fetch live concepts with effective mastery
    concepts = list_concepts(learner_id, course_id)
    concept_map = {c["name"]: c for c in concepts}
    
    syllabus_topics = course.get("syllabusTopics") or []
    if not syllabus_topics:
        syllabus_topics = [c["name"] for c in concepts if c.get("name")]
    if not syllabus_topics:
        syllabus_topics = [course_name]
    
    # Determine exam date: default today + 5 days
    now = datetime.now(timezone.utc)
    if exam_date_iso:
        try:
            exam_dt = datetime.fromisoformat(exam_date_iso.replace("Z", "+00:00"))
        except Exception:
            exam_dt = now + timedelta(days=5)
    elif course.get("examDate"):
        raw_dt = course["examDate"]
        if hasattr(raw_dt, "replace"):
            exam_dt = raw_dt.replace(tzinfo=timezone.utc) if raw_dt.tzinfo is None else raw_dt
        else:
            exam_dt = now + timedelta(days=5)
    else:
        exam_dt = now + timedelta(days=5)

    days_until_exam = max(1, (exam_dt - now).days)
    
    # Priority ranking based on effective mastery
    topic_priorities = []
    for topic in syllabus_topics:
        c_info = concept_map.get(topic)
        eff_mastery = c_info.get("effectiveMastery", 0.5) if c_info else 0.5
        topic_priorities.append({
            "topic": topic,
            "effectiveMastery": eff_mastery,
            "weight": 1.0 - eff_mastery # Lower mastery -> higher priority
        })

    # Sort topics: weakest first
    topic_priorities.sort(key=lambda x: x["weight"], reverse=True)

    # Build schedule blocks
    scheduled_blocks = []
    calendar_events = []
    
    # Generate spaced sessions across the remaining days (up to 3 prioritized sessions)
    session_num = 1
    total_slots = min(3, max(1, days_until_exam))
    for day_offset in range(1, total_slots + 1):
        session_date = now + timedelta(days=day_offset)
        # Morning session (10:00 AM IST)
        session_start = session_date.replace(hour=4, minute=30, second=0, microsecond=0) # 10:00 AM IST is 04:30 UTC
        
        # Pick top priority topics (weak concepts get multiple sessions)
        idx = (day_offset - 1) % len(topic_priorities)
        target_topic = topic_priorities[idx]["topic"]
        mastery_val = topic_priorities[idx]["effectiveMastery"]
        
        event_title = f"{course_name} Revision: {target_topic} (Mastery: {int(mastery_val * 100)}%)"
        event_desc = f"Targeted revision block generated by Agentic Learning Coach for {target_topic} prior to exam on {exam_dt.strftime('%b %d, %Y')}."
        
        try:
            cal_res = create_revision_event(
                title=event_title,
                start_iso=session_start.isoformat(),
                duration_minutes=45,
                description=event_desc
            )
            calendar_events.append(cal_res)
        except Exception as e:
            print(f"Notice: Calendar creation fallback for '{event_title}': {e}")
            cal_res = {
                "id": f"cal-local-{session_num}",
                "summary": event_title,
                "start": session_start.isoformat(),
                "status": "planned"
            }
            calendar_events.append(cal_res)

        scheduled_blocks.append({
            "session": session_num,
            "topic": target_topic,
            "effectiveMastery": mastery_val,
            "startTime": session_start.isoformat(),
            "durationMinutes": 45,
            "calendarEventId": cal_res.get("id")
        })
        session_num += 1

        # For very weak topics (< 0.45), add an extra evening drill block
        if mastery_val < 0.45:
            eve_start = session_date.replace(hour=13, minute=30, second=0, microsecond=0) # 7:00 PM IST is 13:30 UTC
            eve_title = f"[{course_name}] Drill: {target_topic} Deep Dive"
            try:
                eve_cal = create_revision_event(
                    title=eve_title,
                    start_iso=eve_start.isoformat(),
                    duration_minutes=30,
                    description=f"Rapid practice drill for weak concept {target_topic} in {course_name}."
                )
                calendar_events.append(eve_cal)
            except Exception as e:
                eve_cal = {"id": f"cal-local-eve-{session_num}", "summary": eve_title, "status": "planned"}
                calendar_events.append(eve_cal)
                
            scheduled_blocks.append({
                "session": session_num,
                "topic": target_topic,
                "effectiveMastery": mastery_val,
                "startTime": eve_start.isoformat(),
                "durationMinutes": 30,
                "calendarEventId": eve_cal.get("id")
            })
            session_num += 1

    record_event("plan_generated", {
        "learnerId": learner_id,
        "courseId": course_id,
        "examDate": exam_dt.isoformat(),
        "totalBlocks": len(scheduled_blocks)
    })

    return {
        "courseTitle": course.get("title"),
        "examDate": exam_dt.isoformat(),
        "totalSessions": len(scheduled_blocks),
        "scheduledBlocks": scheduled_blocks,
        "calendarEventsCreated": len(calendar_events)
    }
